# 1.1 numpy & pandas 有什么用？

# 1.2 numpy & pandas 安装

google numpy install >getting numpy>source file>numpy >version 

pycharm 里 import

anaconda import 即可

mac sudo pip3 install numpy

windows pip install numpy

pandas python download

# 2.1 numpy 属性

In [1]:
import numpy as np

矩阵，数组运算

In [2]:
array=np.array([[1,2,3],
               [2,3,4]])
print(array)

[[1 2 3]
 [2 3 4]]


In [4]:
print('number of dim:',array.ndim)
print('shape:',array.shape)
print('size:',array.size)

number of dim: 2
shape: (2, 3)
size: 6


# 2.2 numpy 创建array

In [1]:
import numpy as np

In [6]:
a=np.array([2,23,4])

In [7]:
print(a)

[ 2 23  4]


In [8]:
a=np.array([2,23,4],dtype=np.int)
print(a.dtype)

int32


In [11]:
a=np.array([2,23,4],dtype=np.float)
print(a.dtype)

float64


In [9]:
a=np.array([2,23,4],dtype=np.int64)
print(a.dtype)

int64


In [10]:
a=np.array([2,23,4],dtype=np.float32)
print(a.dtype)

float32


定义矩阵

In [12]:
a=np.array([[2,23,4],[2,32,4]])
print(a)

[[ 2 23  4]
 [ 2 32  4]]


定义0矩阵

In [14]:
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
a=np.ones((3,4),dtype=np.int16)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [2]:
a=np.empty((3,4))
print(a)

[[1.18550286e-311 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 1.61590357e+184 4.22471562e-090 1.34994229e+161]
 [9.99665362e-048 6.86714895e+169 3.99910963e+252 1.46030983e-319]]


empty:随机生成每一个元素
    如果之前有值，会生成全1矩阵
    选中一块内存进行分配，原始内容是什么就展示什么，不做初始化，random是选中以后随机初始化

empty: 占用的未初始化的内存，值是随机的

In [4]:
a=np.arange(10,20,2)
print(a)

[10 12 14 16 18]


arange:生成数列[下限，上限，步长]

In [5]:
a=np.arange(12).reshape((3,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


reshape: 重新定义形状

In [6]:
a=np.linspace(1,10,20)
print(a)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


linspace:生成线段  设入口参数（a,b,c）,每次增量（b-a）/(c-1)，其中a为左端点，b为右端点，c为线段数，自动匹配步长

In [7]:
a=np.linspace(1,10,5)
print(a)

[ 1.    3.25  5.5   7.75 10.  ]


In [10]:
a=np.linspace(1,10,6).reshape((2,3))
print(a)

[[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]


# 2.3 numpy的基础运算1

In [11]:
import numpy as np

In [13]:
a=np.array([10,20,30,40])
b=np.arange(4)
print(a,b)
c=a+b
print(c)

[10 20 30 40] [0 1 2 3]
[10 21 32 43]


In [14]:
a=np.array([10,20,30,40])
b=np.arange(4)
print(a,b)
c=b**2
print(c)

[10 20 30 40] [0 1 2 3]
[0 1 4 9]


In [15]:
a=np.array([10,20,30,40])
b=np.arange(4)
print(a,b)
c=a*b
print(c)

[10 20 30 40] [0 1 2 3]
[  0  20  60 120]


In [16]:
a=np.array([10,20,30,40])
b=np.arange(4)
print(a,b)
c=10*np.sin(a)
print(c)

[10 20 30 40] [0 1 2 3]
[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [17]:
c=10*np.cos(a)
print(c)

[-8.39071529  4.08082062  1.5425145  -6.66938062]


In [18]:
c=10*np.tan(a)
print(c)

[  6.48360827  22.37160944 -64.05331197 -11.17214931]


In [20]:
print(b)

[0 1 2 3]


In [19]:
print(b<3)

[ True  True  True False]


In [21]:
print(b==3)

[False False False  True]


In [23]:
a=np.array([[1,1],[0,1]])
b=np.arange(4).reshape((2,2))
c=a*b
c_dot=np.dot(a,b)
print(c)
print(c_dot)

[[0 1]
 [0 3]]
[[2 4]
 [2 3]]


In [25]:
a=np.array([[1,1],[0,1]])
b=np.arange(4).reshape((2,2))

print(a)
print(b)

c=a*b
c_dot=np.dot(a,b)
c_dot_2=a.dot(b)

print(c)
print(c_dot)
print(c_dot_2)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]
[[0 1]
 [0 3]]
[[2 4]
 [2 3]]
[[2 4]
 [2 3]]


c=a*b :逐个相乘
np.dot :矩阵相乘

In [26]:
a=np.random.random((2,4))

a=np.random.random((2,4)): random 模块下 random方法

In [27]:
print(a)
print(np.sum(a))
print(np.sum(a,axis=1))
print(np.sum(a,axis=0))
print(np.min(a))
print(np.max(a))

[[0.52547152 0.91483844 0.0451712  0.54340784]
 [0.37086841 0.19203589 0.43843392 0.84478024]]
3.875007453326768
[2.02888899 1.84611846]
[0.89633993 1.10687433 0.48360512 1.38818808]
0.045171195437826994
0.9148384368925643


# 2.4 numpy的基础运算2

In [28]:
A=np.arange(2,14).reshape((3,4))

In [29]:
print(A)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [30]:
print(np.argmin(A))

0


In [31]:
print(np.argmax(A))

11


In [32]:
print(np.mean(A))

7.5


In [34]:
print(A.mean())

7.5


In [36]:
print(np.median(A))

7.5


前缀和：前n项之和

In [37]:
print(A)
print(np.cumsum(A))

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[ 2  5  9 14 20 27 35 44 54 65 77 90]


差分

In [38]:
print(np.diff(A))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


输出非零值对应的行列值

In [40]:
print(np.nonzero(A))

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


矩阵的排序（正序）

In [41]:
A=np.arange(14,2,-1).reshape((3,4))
print(A)
print(np.sort(A))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


矩阵的转置

In [42]:
print(np.transpose(A))

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


In [44]:
print(A.T)

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


矩阵乘法 A^t*A

In [45]:
print((A.T).dot(A))

[[332 302 272 242]
 [302 275 248 221]
 [272 248 224 200]
 [242 221 200 179]]


带通滤波器，截取替换矩阵元素clip(a,a_min,a_max,out=None)

In [46]:
print(np.clip(A,5,9))

[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]


In [47]:
print(A)

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]


axis=0 对列运算，axis=1 对行运算

In [48]:
print(np.mean(A,axis=0))

[10.  9.  8.  7.]


# 2.5 numpy的索引

In [49]:
import numpy as np

In [66]:
A=np.arange(3,15)

In [52]:
print(A)

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [53]:
print(A[3])

6


In [71]:
A=np.arange(3,15).reshape((3,4))
print(A)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [72]:
print(A[2])

[11 12 13 14]


In [56]:
print(A[1][1])

8


In [59]:
print(A[1,1])

8


In [70]:
print(A[2,:])

[11 12 13 14]


In [61]:
print(A[:,1])

[ 4  8 12]


In [62]:
print(A[1,1:3])

[8 9]


for迭代行列

In [63]:
for row in A:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [73]:
for row in A.T:
    print(row)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [64]:
for column in A.T:
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [74]:
##先转置矩阵，再迭代

项目迭代器（先用flat转化为一行）

In [65]:
print(A)
print(A.flatten())
for item in A.flat:
    print(item)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


In [75]:
#A.flat 为迭代器，python的迭代器就是可迭代对象

# 2.6 numpy的array合并

In [91]:
A=np.array([1,1,1])
B=np.array([2,2,2])
#A=A[:,np.newaxis]
#B=B[:,np.newaxis]
C=np.vstack((A,B)) #vertical stack
D=np.hstack((A,B)) #horizontal stack
print(A)
print(B)
print(C)
print(D)
print(A.shape)
print(D.shape)
print(A.shape,D.shape)
print(A.T.shape)


[1 1 1]
[2 2 2]
[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]
(3,)
(6,)
(3,) (6,)
(3,)


In [92]:
print(A[np.newaxis,:])

[[1 1 1]]


In [93]:
print(A[:,np.newaxis])

[[1]
 [1]
 [1]]


In [94]:
A=np.array([1,1,1])[:,np.newaxis]
B=np.array([2,2,2])[:,np.newaxis]

In [95]:
print(A)
print(B)

[[1]
 [1]
 [1]]
[[2]
 [2]
 [2]]


In [96]:
A=np.array([1,1,1])
A=np.array([1,1,1]).reshape(3,1)
print(A)

[[1]
 [1]
 [1]]


In [97]:
A=np.array([1,1,1])
A=np.vstack(A)
print(A)

[[1]
 [1]
 [1]]


In [98]:
print(D.shape)
print(A.shape,D.shape)

(6,)
(3, 1) (6,)


In [99]:
print(A[np.newaxis,:].shape)

(1, 3, 1)


In [100]:
print(A[np.newaxis,:])

[[[1]
  [1]
  [1]]]


A.B 纵向合并

In [101]:
np.column_stack((A,B))

array([[1, 2],
       [1, 2],
       [1, 2]])

In [102]:
np.c_[A,B]

array([[1, 2],
       [1, 2],
       [1, 2]])

d=np.c_[a,b]
e=np.mat(A)

运用hstack进行横向合并，用vstack进行纵向合并

In [107]:
A=np.array([1,1,1])[:,np.newaxis]
B=np.array([2,2,2])[:,np.newaxis]
print(np.hstack((A,A,B)))
print(np.vstack((A,A,B)))

[[1 1 2]
 [1 1 2]
 [1 1 2]]
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]]


用concatenate & axis=0 纵向 axis=1 横向合并

In [106]:
C=np.concatenate((A,B,B,A))
print(C)
C=np.concatenate((A,B,B,A),axis=0)
print(C)
C=np.concatenate((A,B,B,A),axis=1)
print(C)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]
[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


# 2.7 numpy的array分割

In [108]:
A=np.arange(12).reshape((3,4))
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


纵向分割

In [109]:
print(np.split(A,2,axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


横向分割

In [111]:
print(np.split(A,3,axis=0))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


进行不等量分割,列数自定义

In [117]:
np.array_split(A,(1,2,1),axis=0)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([], shape=(0, 4), dtype=int32),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])]

进行不等量分割,列数随机

In [118]:
print(np.array_split(A,3,axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [114]:
print(np.vsplit(A,3))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [119]:
print(np.hsplit(A,2))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


# 2.8 numpy的copy & deep copy

In [120]:
import numpy as np

In [122]:
a=np.arange(4)

In [123]:
a

array([0, 1, 2, 3])

In [124]:
b=a

In [125]:
c=a

In [126]:
d=b

In [127]:
a[0]=0.3

In [128]:
a

array([0, 1, 2, 3])

In [129]:
a[0]=11

In [130]:
a

array([11,  1,  2,  3])

In [131]:
b is a

True

In [132]:
b

array([11,  1,  2,  3])

In [133]:
c

array([11,  1,  2,  3])

In [134]:
d is a

True

In [135]:
a==b

array([ True,  True,  True,  True])

In [141]:
d[1:3]=[22,33]

In [142]:
a

array([11, 22, 33,  3])

In [144]:
b

array([11,  1,  2,  3])

In [145]:
c

array([11, 22, 33,  3])

python中的变量是地址，指针对象指向地址

In [136]:
b=a.copy() #deep copy

只copy值，不关联

In [137]:
b

array([11,  1,  2,  3])

In [138]:
a[1]=2

In [139]:
b

array([11,  1,  2,  3])

In [140]:
a

array([11,  2,  2,  3])